# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/MicroBlaze_HBM_Streams/MicroBlaze_HBM_Streams.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams || ORIG_REF_NAME==MicroBlaze_HBM_Streams} -quiet] -quiet

# IP: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_hbm_0_0/MicroBlaze_HBM_Streams_hbm_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_hbm_0_0 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_hbm_0_0} -quiet] -quiet

# IP: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_axi_dma_0_1/MicroBlaze_HBM_Streams_axi_dma_0_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_axi_dma_0_1 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_axi_dma_0_1} -quiet] -quiet

# IP: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_axi_traffic_gen_0_0/MicroBlaze_HBM_Streams_axi_traffic_gen_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_axi_traffic_gen_0_0 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_axi_traffic_gen_0_0} -quiet] -quiet

# IP: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_rst_Clk_100M_0/MicroBlaze_HBM_Streams_rst_Clk_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_rst_Clk_100M_0 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_rst_Clk_100M_0} -quiet] -quiet

# IP: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_xbar_2/MicroBlaze_HBM_Streams_xbar_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_xbar_2 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_xbar_2} -quiet] -quiet

# IP: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_microblaze_0_axi_periph_1/MicroBlaze_HBM_Streams_microblaze_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_microblaze_0_axi_periph_1 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_microblaze_0_axi_periph_1} -quiet] -quiet

# IP: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_axi_mem_intercon_2/MicroBlaze_HBM_Streams_axi_mem_intercon_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_axi_mem_intercon_2 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_axi_mem_intercon_2} -quiet] -quiet

# IP: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_xbar_3/MicroBlaze_HBM_Streams_xbar_3.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_xbar_3 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_xbar_3} -quiet] -quiet

# IP: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_microblaze_0_2/MicroBlaze_HBM_Streams_microblaze_0_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_microblaze_0_2 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_microblaze_0_2} -quiet] -quiet

# IP: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_dlmb_v10_1/MicroBlaze_HBM_Streams_dlmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_dlmb_v10_1 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_dlmb_v10_1} -quiet] -quiet

# IP: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_ilmb_v10_1/MicroBlaze_HBM_Streams_ilmb_v10_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_ilmb_v10_1 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_ilmb_v10_1} -quiet] -quiet

# IP: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_dlmb_bram_if_cntlr_1/MicroBlaze_HBM_Streams_dlmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_dlmb_bram_if_cntlr_1 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_dlmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_ilmb_bram_if_cntlr_1/MicroBlaze_HBM_Streams_ilmb_bram_if_cntlr_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_ilmb_bram_if_cntlr_1 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_ilmb_bram_if_cntlr_1} -quiet] -quiet

# IP: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_lmb_bram_1/MicroBlaze_HBM_Streams_lmb_bram_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_lmb_bram_1 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_lmb_bram_1} -quiet] -quiet

# IP: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_MB_Debug_0_0/MicroBlaze_HBM_Streams_MB_Debug_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_MB_Debug_0_0 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_MB_Debug_0_0} -quiet] -quiet

# IP: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_clk_wiz_0_0/MicroBlaze_HBM_Streams_clk_wiz_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_clk_wiz_0_0 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_clk_wiz_0_0} -quiet] -quiet

# IP: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_resetn_inv_0_0/MicroBlaze_HBM_Streams_resetn_inv_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_resetn_inv_0_0 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_resetn_inv_0_0} -quiet] -quiet

# IP: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_auto_pc_0/MicroBlaze_HBM_Streams_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_auto_pc_0 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_auto_pc_0} -quiet] -quiet

# IP: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_auto_us_0/MicroBlaze_HBM_Streams_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_auto_us_0 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_auto_us_0} -quiet] -quiet

# IP: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_auto_ds_0/MicroBlaze_HBM_Streams_auto_ds_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_auto_ds_0 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_auto_ds_0} -quiet] -quiet

# IP: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_auto_pc_1/MicroBlaze_HBM_Streams_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_auto_pc_1 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_auto_pc_1} -quiet] -quiet

# XDC: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_hbm_0_0/hdl/par/hbm_ip.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_hbm_0_0 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_hbm_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_hbm_0_0/hdl/par/MicroBlaze_HBM_Streams_hbm_0_0_ooc.xdc

# XDC: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_axi_dma_0_1/MicroBlaze_HBM_Streams_axi_dma_0_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_axi_dma_0_1 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_axi_dma_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_axi_dma_0_1/MicroBlaze_HBM_Streams_axi_dma_0_1_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_axi_dma_0_1 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_axi_dma_0_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_axi_traffic_gen_0_0/MicroBlaze_HBM_Streams_axi_traffic_gen_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_axi_traffic_gen_0_0 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_axi_traffic_gen_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_rst_Clk_100M_0/MicroBlaze_HBM_Streams_rst_Clk_100M_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_rst_Clk_100M_0 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_rst_Clk_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_rst_Clk_100M_0/MicroBlaze_HBM_Streams_rst_Clk_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_rst_Clk_100M_0 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_rst_Clk_100M_0} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_xbar_3/MicroBlaze_HBM_Streams_xbar_3_ooc.xdc

# XDC: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_microblaze_0_2/MicroBlaze_HBM_Streams_microblaze_0_2.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_microblaze_0_2 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_microblaze_0_2} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_microblaze_0_2/MicroBlaze_HBM_Streams_microblaze_0_2_ooc_debug.xdc

# XDC: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_microblaze_0_2/MicroBlaze_HBM_Streams_microblaze_0_2_ooc.xdc

# XDC: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_dlmb_v10_1/MicroBlaze_HBM_Streams_dlmb_v10_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_dlmb_v10_1 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_dlmb_v10_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_dlmb_v10_1/MicroBlaze_HBM_Streams_dlmb_v10_1_ooc.xdc

# XDC: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_ilmb_v10_1/MicroBlaze_HBM_Streams_ilmb_v10_1.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_ilmb_v10_1 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_ilmb_v10_1} -quiet] {/U0 } ]/U0 ] -quiet] -quiet

# XDC: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_ilmb_v10_1/MicroBlaze_HBM_Streams_ilmb_v10_1_ooc.xdc

# XDC: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_dlmb_bram_if_cntlr_1/MicroBlaze_HBM_Streams_dlmb_bram_if_cntlr_1_ooc.xdc

# XDC: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_ilmb_bram_if_cntlr_1/MicroBlaze_HBM_Streams_ilmb_bram_if_cntlr_1_ooc.xdc

# XDC: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_lmb_bram_1/MicroBlaze_HBM_Streams_lmb_bram_1_ooc.xdc

# XDC: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_clk_wiz_0_0/MicroBlaze_HBM_Streams_clk_wiz_0_0_board.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_clk_wiz_0_0 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_clk_wiz_0_0/MicroBlaze_HBM_Streams_clk_wiz_0_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_clk_wiz_0_0 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_clk_wiz_0_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_clk_wiz_0_0/MicroBlaze_HBM_Streams_clk_wiz_0_0_ooc.xdc

# XDC: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_auto_pc_0/MicroBlaze_HBM_Streams_auto_pc_0_ooc.xdc

# XDC: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_auto_us_0/MicroBlaze_HBM_Streams_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_auto_us_0 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_auto_us_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_auto_us_0/MicroBlaze_HBM_Streams_auto_us_0_ooc.xdc

# XDC: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_auto_ds_0/MicroBlaze_HBM_Streams_auto_ds_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==MicroBlaze_HBM_Streams_auto_ds_0 || ORIG_REF_NAME==MicroBlaze_HBM_Streams_auto_ds_0} -quiet] {/inst } ]/inst ] -quiet] -quiet

# XDC: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_auto_ds_0/MicroBlaze_HBM_Streams_auto_ds_0_ooc.xdc

# XDC: bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_auto_pc_1/MicroBlaze_HBM_Streams_auto_pc_1_ooc.xdc

# XDC: bd/MicroBlaze_HBM_Streams/MicroBlaze_HBM_Streams_ooc.xdc
