# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
set_param chipscope.maxJobs 10
set_param power.BramSDPPropagationFix 1
set_param power.enableUnconnectedCarry8PinPower 1
set_param power.enableCarry8RouteBelPower 1
set_param power.enableLutRouteBelPower 1
set_param ced.repoPaths /home/jdumont/.Xilinx/Vivado/2019.2/xhub/ced_store
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xcu280-fsvh2892-2L-e

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.cache/wt [current_project]
set_property parent.project_path /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part xilinx.com:au280:part0:1.1 [current_project]
set_property ip_repo_paths /work/jdumont/workspaces/vivado/ip_repo/MB_Debug_1.0 [current_project]
update_ip_catalog
set_property ip_output_repo /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/hdl/MicroBlaze_HBM_Streams_wrapper.vhd
add_files /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/MicroBlaze_HBM_Streams.bd
set_property used_in_implementation false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_hbm_0_0/hdl/par/hbm_ip.xdc]
set_property used_in_implementation false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_hbm_0_0/hdl/par/MicroBlaze_HBM_Streams_hbm_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_axi_dma_0_1/MicroBlaze_HBM_Streams_axi_dma_0_1.xdc]
set_property used_in_implementation false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_axi_dma_0_1/MicroBlaze_HBM_Streams_axi_dma_0_1_clocks.xdc]
set_property used_in_implementation false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_axi_traffic_gen_0_0/MicroBlaze_HBM_Streams_axi_traffic_gen_0_0.xdc]
set_property used_in_implementation false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_rst_Clk_100M_0/MicroBlaze_HBM_Streams_rst_Clk_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_rst_Clk_100M_0/MicroBlaze_HBM_Streams_rst_Clk_100M_0.xdc]
set_property used_in_implementation false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_xbar_3/MicroBlaze_HBM_Streams_xbar_3_ooc.xdc]
set_property used_in_implementation false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_microblaze_0_2/MicroBlaze_HBM_Streams_microblaze_0_2.xdc]
set_property used_in_implementation false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_microblaze_0_2/MicroBlaze_HBM_Streams_microblaze_0_2_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_microblaze_0_2/MicroBlaze_HBM_Streams_microblaze_0_2_ooc.xdc]
set_property used_in_implementation false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_dlmb_v10_1/MicroBlaze_HBM_Streams_dlmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_dlmb_v10_1/MicroBlaze_HBM_Streams_dlmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_ilmb_v10_1/MicroBlaze_HBM_Streams_ilmb_v10_1.xdc]
set_property used_in_implementation false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_ilmb_v10_1/MicroBlaze_HBM_Streams_ilmb_v10_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_dlmb_bram_if_cntlr_1/MicroBlaze_HBM_Streams_dlmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_ilmb_bram_if_cntlr_1/MicroBlaze_HBM_Streams_ilmb_bram_if_cntlr_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_lmb_bram_1/MicroBlaze_HBM_Streams_lmb_bram_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_clk_wiz_0_0/MicroBlaze_HBM_Streams_clk_wiz_0_0_board.xdc]
set_property used_in_implementation false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_clk_wiz_0_0/MicroBlaze_HBM_Streams_clk_wiz_0_0.xdc]
set_property used_in_implementation false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_clk_wiz_0_0/MicroBlaze_HBM_Streams_clk_wiz_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_auto_pc_0/MicroBlaze_HBM_Streams_auto_pc_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_auto_us_0/MicroBlaze_HBM_Streams_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_auto_us_0/MicroBlaze_HBM_Streams_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_auto_us_0/MicroBlaze_HBM_Streams_auto_us_0_ooc.xdc]
set_property used_in_synthesis false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_auto_ds_0/MicroBlaze_HBM_Streams_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_auto_ds_0/MicroBlaze_HBM_Streams_auto_ds_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_auto_ds_0/MicroBlaze_HBM_Streams_auto_ds_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_auto_pc_1/MicroBlaze_HBM_Streams_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/MicroBlaze_HBM_Streams_ooc.xdc]
set_property used_in_implementation false [get_files -all /work/jdumont/workspaces/vivado/HBM_MB_Stream_test/HBM_MB_Stream_test.srcs/sources_1/bd/MicroBlaze_HBM_Streams/ip/MicroBlaze_HBM_Streams_microblaze_0_2/data/mb_bootloop_le.elf]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

synth_design -top MicroBlaze_HBM_Streams_wrapper -part xcu280-fsvh2892-2L-e


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MicroBlaze_HBM_Streams_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MicroBlaze_HBM_Streams_wrapper_utilization_synth.rpt -pb MicroBlaze_HBM_Streams_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
